public class StudentRunner {
    public static void main(String[] args)
{
	String course = "Computer Science and Engineering";
	System.out.println(course);
	String college="AdiChunchangiri Institue of Technology";
	System.out.println(college);
	String place="Chikkamagaluru";
	System.out.println(place);
	String batch="2020";
	System.out.println(batch);
	String completionYear="2024";
	System.out.println(completionYear);
	String CGPA="8";
	System.out.println(CGPA);
	String studentName="Sapnaz Banu I";
	System.out.println(studentName);
	String studentAge="21";
	System.out.println(studentAge);
	String phrase = "Programming";
	System.out.println(phrase);
	String fruits = "apple,banana,cherry";
	System.out.println(fruits);
	String words = "Hello world";
	System.out.println(words);
	String message = "Java is fun!";
	System.out.println(message);
	String sentence = "I love programming";
	System.out.println(sentence);
	String message1="tomorrow belongs to those who prepare for it today";
	System.out.println(message);
	String favColour="blue";
	System.out.println(favColour);
	String nationalAniaml="Bengal Tiger";
	System.out.println(nationalAniaml);
	String indiasCapitalCity="Delhi";
	System.out.println(indiasCapitalCity);
	String favCountry="Turkey";
	System.out.println(favCountry);
	String traditions="India";
	System.out.println(traditions);
	String laptop="Lenovo";
	System.out.println(laptop);
	String goal="Success";
	System.out.println(goal);
	String fatherName="Ismail";
	System.out.println(fatherName);
	String motherName="Sahira Banu";
	System.out.println(motherName);
	String engineer="computer science";
	System.out.println(engineer);
	String studying="in benagaluru";
	System.out.println(studying);
	String friends="Extended Family";
	System.out.println(friends);
	String nationalBird="peacock";
	System.out.println(nationalBird);
	String nationalAnthem="jana gana mana";
	System.out.println(nationalAnthem);
	String president="Droupadi murumuru";
	System.out.println(president);
	String android="Samsung";
	System.out.println(android);
	String ios="apple";
	System.out.println(ios);
	String brand="ZARA";
	System.out.println(brand);
	String university="VTU";
	System.out.println(university);
	String pm="Narendra Modi";
	System.out.println(pm);
	String movie="Bahubali";
	System.out.println(movie);
	String friends2="movie";
	System.out.println(friends);
	String grade="A";
	System.out.println(grade);
	String delhi="Capital City";
	System.out.println(delhi);
	String cm="siddaramaiyya";
	System.out.println(cm);
	String bengaluru="CapitalCity";
	System.out.println(bengaluru);
	String author="khalid husseini";
	System.out.println(author);
	String favBook="Kite Runner";
	System.out.println(favBook);
	String certification="SAP Tool";
	System.out.println(certification);
	String motheTongue="Urdu";
	System.out.println(motheTongue);
	String taluk="kadur";
	System.out.println(taluk);
	String karnataka="State";
	System.out.println(karnataka);
	String nativePlace="Kadur";
	System.out.println(nativePlace);
	String juice="mango";
	System.out.println(juice);
	String bag="sky bags";
	System.out.println(bag);
	String vanilla="Ice-cream";
	System.out.println(vanilla);
	String fruit="Apple";
	System.out.println(fruit);
	String IOT="IoT refers to a network of interconnected devices that can communicate and exchange data, enhancing efficiency and convenience.";
	System.out.println(IOT);
	String Platypus="Found only in Australia, platypuses are unique for laying eggs despite being mammals. They also have a duck-like bill and are one of the few venomous mammals.";
	System.out.println(Platypus);
	String chocolate="DIary Milk";
	System.out.println(chocolate);
	String food="Indian";
	System.out.println(food);
	String designation="Software Engineer";
	System.out.println(designation);
	String status="Un-married";
	System.out.println(status);
	String operatingSystem="Windows";
	System.out.println(operatingSystem);
	String browser="google";
	System.out.println(browser);
	String bankBalanace="two thousand";
	System.out.println(bankBalanace);
	String account="Canara Bank";
	System.out.println(account);
	String spect="lens kart";
	System.out.println(spect);
	String mountains="mount everest";
	System.out.println(mountains);
	String ladakh="Love";
	System.out.println(ladakh);
	String longestRiver="Nile";
	System.out.println(longestRiver);
	String makeup="Lakme";
	System.out.println(makeup);
	String zudio="Clothes";
	System.out.println(zudio);
	String dessert="sahara";
	System.out.println(dessert);
	String cake="Lava";
	System.out.println(cake);
	String fan="Usha";
	System.out.println(fan);
	String waterBottle="Cello";
	System.out.println(waterBottle);
	String jacket="PUMA";
	System.out.println(jacket);
	String slippers="CROCS";
	System.out.println(slippers);
	String lockers="godrej";
	System.out.println(lockers);
	String grinder="Preethi";
	System.out.println(grinder);
	String size="M";
	System.out.println(size);
	String light="Syska";
	System.out.println(light);
	String bed="SleepWell";
	System.out.println(bed);
	
	
	
	String firstName="Sapnaz";
	String lastName="Banu";
	String fullName=firstName+lastName;
	System.out.println(fullName);
	String fatherName1="Ismail";
	String motherName2="Sahira";
	String family=fatherName1 + motherName2;
	System.out.println(family);
	String internship1="SAP tool";
	String internship2="CVAT tool";
	String internship=internship1 + internship2;
	System.out.println(internship);
	String textBook="NCERT";
	String noteBook="Arun";
	String book=textBook + noteBook;
	System.out.println(book);
	String dentalDoctor="Neha";
	String skinDoctor="Megha";
	String doctor=dentalDoctor + skinDoctor;
	System.out.println(doctor);
	String favCricketer1="Dhoni";
	String favCricketer2="Kohli";
	String cketer=favCricketer1 + favCricketer2;
	System.out.println(cketer);
	String favActor="punith";
	String favActress="Ramya";
	String Actors=favActor + favActress;
	System.out.println(Actors);
	String movieHindi="DDLJ";
	String movieKannada="RAM";
	String movies=movieHindi+movieKannada;
	System.out.println(movies);
	String favColour1="pink";
	String favColour2="Blue";
	String favColours=favColour1 +favColour2;
	System.out.println(favColours);
	String phoneNo="1234567893";
	String alternativeNo="7865894356";
	String finalNumber=phoneNo + alternativeNo;
	System.out.println(finalNumber);
	String doorNo1="6758";
	String doorNo2="2521";
	String doorNo=doorNo1 + doorNo2;
	System.out.println(doorNo);
	String bride="chappu";
	String groom="mus";
	String wedding=bride + groom;
	System.out.println(wedding);
	String tour1="Shimal";
	String tour2="Manali";
	String visited=tour1 + tour2;
	System.out.println(visited);
	String author1="Collen";
	String author2="Khalid";
	String authors=author1 + author2;
	System.out.println(authors);
	String colour1="Pink";
	String colour2="Black";
	String colours=colour1 + colour2;
	System.out.println(colours);
	String phoneIos="Apple";
	String phoneAndroid="samsung";
	String phone=phoneIos + phoneAndroid;
	System.out.println(phone);
	String laptops="mi";
	String tab="HP";
	String gadget=laptop + tab;
	System.out.println(gadget);
	String dressSize1="M";
	String dressSize2="S";
	String dressSize=dressSize1 + dressSize2;
	System.out.println(dressSize);
	String shoeSize1="8";
	String shoeSize2="9";
	String shoeSize=shoeSize1 + shoeSize2;
	System.out.println(shoeSize);
	String menCream="Garnier";
	String femaleCream="Lakme";
	String Cream=menCream + femaleCream;
	System.out.println(Cream);
	String exp1="+";
	String exp2="-";
	String arithmeticExpression=exp1 + exp2;
	System.out.println( arithmeticExpression);
	String nationalBird1="peacock";
	String nationalAnimal="tiger";
	String national=nationalBird1 + nationalAnimal;
	System.out.println(national);
	String foodType1="puri";
	String foodType2="pullav";
	String foods=foodType1 + foodType1;
	System.out.println(foods);
	String fruitType1="Mango";
	String fruitType2="Banana";
	String healthy=fruitType1 + fruitType1;
	System.out.println(healthy);
	String height1="155cm";
	String height2="176cm";
	String height=height1+height2;
	System.out.println(height);
	String resultPuc="90%";
	String resultDegree="85%";
	String result=resultPuc + resultDegree;
	System.out.println(result);
	String employeeId1="abcd";
	String employeeId2="efgt";
	String employeeId=employeeId1 + employeeId2;
	System.out.println(employeeId);
	String male="Nithin";
	String female="Geetha";
	String people=male + female;
	System.out.println(people);
	String cupCake1="Vanilla";
	String cupCake2="Chocolate";
	String cakesFinal=cupCake1 + cupCake2;
	System.out.println(cakesFinal);
	String maritalStatus1="married";
	String maritalStatus2="unmarried";
	String maritalStatus=maritalStatus1 +maritalStatus2;
	System.out.println(maritalStatus);
	String phase1="project";
	String phase2="project";
	String finalProject=phase1 +phase2;
	System.out.println(finalProject);
	String algorithm1="CNN";
	String algorithm2="KNN";
	String algorithms=algorithm1 +algorithm2;
	System.out.println(algorithms);
	String cgpa1="9";
	String cgpa2="8";
	String fcd= cgpa1 + cgpa1;
	System.out.println(fcd);
	String citizenShip1="India";
	String citizenShip2="America";
	String citizenShip=citizenShip1 +citizenShip2;
	System.out.println(citizenShip);
	String trainers1="omkar";
	String trainers2="Harisha";
	String trainers=trainers1 +trainers2;
	System.out.println(trainers);
	String gender1="male";
	String gender2="female";
	String gender=gender1 +gender2;
	System.out.println(gender);
	String mail1="sapna@123";
	String mail2="banu@123";
	String mail= mail1 + mail2;
	System.out.println( mail);
	String dress1="western";
	String dress2="traditional";
	String dress= dress1 +dress2;
	System.out.println(dress);
	String favBook1="last queen";
	String favBook2=" Ends with us";
	String favBooks=favBook1 +favBook2;
	System.out.println(favBooks);
	String person1="dancing";
	String person2="singing";
	String peopleFinal=person1 + person2;
	System.out.println(peopleFinal);
	String light1="LED";
	String light2="zero bulb";
	String lights= light1 + light2;
	System.out.println(lights);
	String assignment1="home 1";
	String assignment2="home 2";
	String assassignments=assignment1+assignment2;
	System.out.println(assassignments);
	String movie1="kgf1";
	String movie2="kgf2";
	String moviesFinal=movie1 +movie2;
	System.out.println(moviesFinal);
	String water1="hot";
	String water2="cold";
	String water=water1 +water2;
	System.out.println(water);
	String house1="flat";
	String house2="home";
	String house=house1 +house2;
	System.out.println(house);
	String jewellery1="silver";
	String jewellery2="gold";
	String jewellery=jewellery1 +jewellery2;
	System.out.println(jewellery);
	String road1="Highway";
	String road2="service road";
	String road=road1 +road2;
	System.out.println(road);
	String travel1="paris";
	String travel2="london";
	String destination= travel1 +  travel2;
	System.out.println(destination);
	String city1="Bengaluru";
	String city2="Mumbai";
	String city=city1 + city2;
	System.out.println(city);
	String locations1= "Mountain";
	String locations2= "Beach";
	String locationsFinal=locations1 +locations2;
	System.out.println(locationsFinal);
	String journey1="by Train";
	String journey2= "by Flight";
	String journey=journey1 +journey2;
	System.out.println(journey);
	String singer="Shakira";
	String dancer="Ariana";
	String concert=singer +dancer;
	System.out.println(concert);
	String mall1="G T";
	String mall2="Orion";
	String location=mall1 + mall2;
	System.out.println(location);
	String life1="hard";
	String life2="easy";
	String life=life1 + life2;
	System.out.println(life);
	String story1="happy ending";
	String story2="sad ending";
	String climax=story1 +story2;
	System.out.println(climax);
	String subject1="science";
	String subject2="maths";
	String subject=subject1 +subject2;
	System.out.println(subject);
	String network1="airtel";
	String network2="jio";
	String network=network1 + network2;
	System.out.println(network);
	String student1="class 10th";
	String student2="class 9th";
	String totalStudents=student1 + student2;
	System.out.println(totalStudents);
	String exam1="JEE";
	String exam2="CET";
	String exams=exam1 +exam2;
	System.out.println(exams);
	String room1="empty";
	String room2="full";
	String rooms=room1+"and"+room2;
	System.out.println();
	String packet1="5";
	String packet2="10";
	String totalPackets=packet1 + packet2;
	System.out.println(totalPackets);
	String red="stop";
	String green="move";
	String trafficSignal=red + green;
	System.out.println(trafficSignal);
	String yellow="get ready";
	String trafficSignals=red + yellow + green;
	System.out.println(trafficSignals);
	String nivea="Cream";
	String dove="bodlotion";
	String cosmetics=nivea + dove;
	System.out.println( cosmetics);
	String puma="shoe brand";
	String zara="Clothing brand";
	String bigBrands=puma +"and"+zara;
	System.out.println();
	String letters="26";
	String ovels="6";
	String total=letters + ovels;
	System.out.println(total);
	String sum=" 5 chocolates";
	String sub="3 chocolates";
	String totals=sum+"and"+sub;
	System.out.println(totals);
	String orange="tasty fruit";
	String pineAplle="tangy fruit";
	String tastes=orange + pineAplle;
	System.out.println(tastes);
	String mirror1="square";
	String mirror2="circle";
	String mirrors=mirror1 +mirror2;
	System.out.println(mirrors);
	String soap1 ="Dove";
	String soap2="Lux";
	String soaps=soap1 + soap2;
	System.out.println(soaps);
	String bottle1="Steel";
	String bottle2="plastic";
	String bottle=bottle1 + bottle2;
	System.out.println(bottle);
	String mainChar1="alam";
	String mainChar2="bebo";
	String heeraMandi=mainChar1 + mainChar2;
	System.out.println();
	String laptop1="HP";
	String laptop2="Dell";
	String laotops=laptop1 +laptop2;
	System.out.println(laptop);
	String snack1="chips";
	String snack2="breads";
	String snacks=snack1 + snack2;
	System.out.println(snacks);
	String degree1="Engineering";
	String degree2="BCA";
	String degrees=degree1 +degree2;
	System.out.println(degrees);

	
	
	
	
	
	
	
	
	
	
	
	
}
}
	
	