package com.xworkz.lombokproject.dto;

public enum Location {

	DRRAJKUMARROAD, SAMPIGEROAD, WHITEFIELD, MAGADIMAINROAD, HOSURROAD, WHITEFIELDMAINROAD,
	PLATFORMROAD, OLDMADRASROAD, NAGASANDRA, UBCITY, ARKEREROARD;

}